version: "3.3"

services:

  worker:
    build:
      context: "."
    command: /start.sh
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 14G
        reservations:
          cpus: '0.10'
          memory: 1G  
    extra_hosts:
        - 'aprov.database.windows.net:10.40.1.4'
        - 'aprovdev.database.windows.net:10.41.5.4'
    networks:
      - ufinetnetwork
    env_file:
      - .env
networks:
  ufinetnetwork:
    external: true


# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.252.0/24
